#!/bin/bash
#
#	just test2ing
#

shopt -s extglob

COMMAND="grpkg test2"
VERSION_NUMBER="v20250512-1"

DEBUG=""
VERSION=""

version () {
	echo -e "$COMMAND: $VERSION_NUMBER"
}

description () {
	echo -e "$COMMAND: run a simple test2 case"
}

usage () {
	echo "usage: $COMMAND {<case>|-v|--version}"
	echo
	echo "where:"
	echo "   <case>          name of the test2 case"
	echo "   -V|--version    version of the this command"
}

set -x
declare -a ARGS
declare -a OPTIONS
ARGS=( $@ )
for ii in ${ARGS[@]}
do
	case $ii in
	-D|--debug)	DEBUG="debug"
			;;
	-v|--verbose)	VERBOSE="verbose"
			;;
	*)
		OPTIONS+=( $ii )
	esac
done

for ii in ${OPTIONS[@]}
do
	case $ii in
	-\?|-h|--help)
		usage
		exit 0
		;;

	-V|--version)
		version
		exit 0
		;;
	
	-d|--description)
		description
		exit 0
		;;

	-*)	echo -e "no such option: $ii"
		exit 1
		;;

	esac
done

echo "$COMMAND: default: list all the possible test2 cases"
exit $?

